### ISSUE TITLE
Minor Typo for "intertools" (which should be "itertools") in Density-clustering ipynb

### ISSUE THREAD

**Issue by kfoofw** [lighthouse-labs/unsupervised_learning_exercise#1]
Current activity ipynb for DBSCAN has an instructional step: 
`"combinations (hint: use 'product' function from 'intertools')"`

Some student was confused about intertools and couldn't find information about it, which caused some unnecessary time wastage. This just requires a quick fix change to "itertools".

**Comment by jurajkapasny** [comment]
fixed. Thanks!!
